// Code generated by ent, DO NOT EDIT.

package supplierprofile

import (
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
)

// ID filters vertices based on their ID field.
func ID(id int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldID, id))
}

// IDEQ applies the EQ predicate on the ID field.
func IDEQ(id int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldID, id))
}

// IDNEQ applies the NEQ predicate on the ID field.
func IDNEQ(id int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldID, id))
}

// IDIn applies the In predicate on the ID field.
func IDIn(ids ...int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldID, ids...))
}

// IDNotIn applies the NotIn predicate on the ID field.
func IDNotIn(ids ...int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldID, ids...))
}

// IDGT applies the GT predicate on the ID field.
func IDGT(id int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldID, id))
}

// IDGTE applies the GTE predicate on the ID field.
func IDGTE(id int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldID, id))
}

// IDLT applies the LT predicate on the ID field.
func IDLT(id int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldID, id))
}

// IDLTE applies the LTE predicate on the ID field.
func IDLTE(id int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldID, id))
}

// UserID applies equality check predicate on the "user_id" field. It's identical to UserIDEQ.
func UserID(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldUserID, v))
}

// CompanyName applies equality check predicate on the "company_name" field. It's identical to CompanyNameEQ.
func CompanyName(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldCompanyName, v))
}

// ContactName applies equality check predicate on the "contact_name" field. It's identical to ContactNameEQ.
func ContactName(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldContactName, v))
}

// ContactEmail applies equality check predicate on the "contact_email" field. It's identical to ContactEmailEQ.
func ContactEmail(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldContactEmail, v))
}

// ContactPhone applies equality check predicate on the "contact_phone" field. It's identical to ContactPhoneEQ.
func ContactPhone(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldContactPhone, v))
}

// Status applies equality check predicate on the "status" field. It's identical to StatusEQ.
func Status(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldStatus, v))
}

// AccountSubmissionEnabled applies equality check predicate on the "account_submission_enabled" field. It's identical to AccountSubmissionEnabledEQ.
func AccountSubmissionEnabled(v bool) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldAccountSubmissionEnabled, v))
}

// Notes applies equality check predicate on the "notes" field. It's identical to NotesEQ.
func Notes(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldNotes, v))
}

// ReviewNote applies equality check predicate on the "review_note" field. It's identical to ReviewNoteEQ.
func ReviewNote(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldReviewNote, v))
}

// ReviewedAt applies equality check predicate on the "reviewed_at" field. It's identical to ReviewedAtEQ.
func ReviewedAt(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedBy applies equality check predicate on the "reviewed_by" field. It's identical to ReviewedByEQ.
func ReviewedBy(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldReviewedBy, v))
}

// CreatedAt applies equality check predicate on the "created_at" field. It's identical to CreatedAtEQ.
func CreatedAt(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// UpdatedAt applies equality check predicate on the "updated_at" field. It's identical to UpdatedAtEQ.
func UpdatedAt(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UserIDEQ applies the EQ predicate on the "user_id" field.
func UserIDEQ(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldUserID, v))
}

// UserIDNEQ applies the NEQ predicate on the "user_id" field.
func UserIDNEQ(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldUserID, v))
}

// UserIDIn applies the In predicate on the "user_id" field.
func UserIDIn(vs ...int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldUserID, vs...))
}

// UserIDNotIn applies the NotIn predicate on the "user_id" field.
func UserIDNotIn(vs ...int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldUserID, vs...))
}

// CompanyNameEQ applies the EQ predicate on the "company_name" field.
func CompanyNameEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldCompanyName, v))
}

// CompanyNameNEQ applies the NEQ predicate on the "company_name" field.
func CompanyNameNEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldCompanyName, v))
}

// CompanyNameIn applies the In predicate on the "company_name" field.
func CompanyNameIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldCompanyName, vs...))
}

// CompanyNameNotIn applies the NotIn predicate on the "company_name" field.
func CompanyNameNotIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldCompanyName, vs...))
}

// CompanyNameGT applies the GT predicate on the "company_name" field.
func CompanyNameGT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldCompanyName, v))
}

// CompanyNameGTE applies the GTE predicate on the "company_name" field.
func CompanyNameGTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldCompanyName, v))
}

// CompanyNameLT applies the LT predicate on the "company_name" field.
func CompanyNameLT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldCompanyName, v))
}

// CompanyNameLTE applies the LTE predicate on the "company_name" field.
func CompanyNameLTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldCompanyName, v))
}

// CompanyNameContains applies the Contains predicate on the "company_name" field.
func CompanyNameContains(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContains(FieldCompanyName, v))
}

// CompanyNameHasPrefix applies the HasPrefix predicate on the "company_name" field.
func CompanyNameHasPrefix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasPrefix(FieldCompanyName, v))
}

// CompanyNameHasSuffix applies the HasSuffix predicate on the "company_name" field.
func CompanyNameHasSuffix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasSuffix(FieldCompanyName, v))
}

// CompanyNameEqualFold applies the EqualFold predicate on the "company_name" field.
func CompanyNameEqualFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEqualFold(FieldCompanyName, v))
}

// CompanyNameContainsFold applies the ContainsFold predicate on the "company_name" field.
func CompanyNameContainsFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContainsFold(FieldCompanyName, v))
}

// ContactNameEQ applies the EQ predicate on the "contact_name" field.
func ContactNameEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldContactName, v))
}

// ContactNameNEQ applies the NEQ predicate on the "contact_name" field.
func ContactNameNEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldContactName, v))
}

// ContactNameIn applies the In predicate on the "contact_name" field.
func ContactNameIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldContactName, vs...))
}

// ContactNameNotIn applies the NotIn predicate on the "contact_name" field.
func ContactNameNotIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldContactName, vs...))
}

// ContactNameGT applies the GT predicate on the "contact_name" field.
func ContactNameGT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldContactName, v))
}

// ContactNameGTE applies the GTE predicate on the "contact_name" field.
func ContactNameGTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldContactName, v))
}

// ContactNameLT applies the LT predicate on the "contact_name" field.
func ContactNameLT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldContactName, v))
}

// ContactNameLTE applies the LTE predicate on the "contact_name" field.
func ContactNameLTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldContactName, v))
}

// ContactNameContains applies the Contains predicate on the "contact_name" field.
func ContactNameContains(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContains(FieldContactName, v))
}

// ContactNameHasPrefix applies the HasPrefix predicate on the "contact_name" field.
func ContactNameHasPrefix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasPrefix(FieldContactName, v))
}

// ContactNameHasSuffix applies the HasSuffix predicate on the "contact_name" field.
func ContactNameHasSuffix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasSuffix(FieldContactName, v))
}

// ContactNameEqualFold applies the EqualFold predicate on the "contact_name" field.
func ContactNameEqualFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEqualFold(FieldContactName, v))
}

// ContactNameContainsFold applies the ContainsFold predicate on the "contact_name" field.
func ContactNameContainsFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContainsFold(FieldContactName, v))
}

// ContactEmailEQ applies the EQ predicate on the "contact_email" field.
func ContactEmailEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldContactEmail, v))
}

// ContactEmailNEQ applies the NEQ predicate on the "contact_email" field.
func ContactEmailNEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldContactEmail, v))
}

// ContactEmailIn applies the In predicate on the "contact_email" field.
func ContactEmailIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldContactEmail, vs...))
}

// ContactEmailNotIn applies the NotIn predicate on the "contact_email" field.
func ContactEmailNotIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldContactEmail, vs...))
}

// ContactEmailGT applies the GT predicate on the "contact_email" field.
func ContactEmailGT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldContactEmail, v))
}

// ContactEmailGTE applies the GTE predicate on the "contact_email" field.
func ContactEmailGTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldContactEmail, v))
}

// ContactEmailLT applies the LT predicate on the "contact_email" field.
func ContactEmailLT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldContactEmail, v))
}

// ContactEmailLTE applies the LTE predicate on the "contact_email" field.
func ContactEmailLTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldContactEmail, v))
}

// ContactEmailContains applies the Contains predicate on the "contact_email" field.
func ContactEmailContains(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContains(FieldContactEmail, v))
}

// ContactEmailHasPrefix applies the HasPrefix predicate on the "contact_email" field.
func ContactEmailHasPrefix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasPrefix(FieldContactEmail, v))
}

// ContactEmailHasSuffix applies the HasSuffix predicate on the "contact_email" field.
func ContactEmailHasSuffix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasSuffix(FieldContactEmail, v))
}

// ContactEmailEqualFold applies the EqualFold predicate on the "contact_email" field.
func ContactEmailEqualFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEqualFold(FieldContactEmail, v))
}

// ContactEmailContainsFold applies the ContainsFold predicate on the "contact_email" field.
func ContactEmailContainsFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContainsFold(FieldContactEmail, v))
}

// ContactPhoneEQ applies the EQ predicate on the "contact_phone" field.
func ContactPhoneEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldContactPhone, v))
}

// ContactPhoneNEQ applies the NEQ predicate on the "contact_phone" field.
func ContactPhoneNEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldContactPhone, v))
}

// ContactPhoneIn applies the In predicate on the "contact_phone" field.
func ContactPhoneIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldContactPhone, vs...))
}

// ContactPhoneNotIn applies the NotIn predicate on the "contact_phone" field.
func ContactPhoneNotIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldContactPhone, vs...))
}

// ContactPhoneGT applies the GT predicate on the "contact_phone" field.
func ContactPhoneGT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldContactPhone, v))
}

// ContactPhoneGTE applies the GTE predicate on the "contact_phone" field.
func ContactPhoneGTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldContactPhone, v))
}

// ContactPhoneLT applies the LT predicate on the "contact_phone" field.
func ContactPhoneLT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldContactPhone, v))
}

// ContactPhoneLTE applies the LTE predicate on the "contact_phone" field.
func ContactPhoneLTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldContactPhone, v))
}

// ContactPhoneContains applies the Contains predicate on the "contact_phone" field.
func ContactPhoneContains(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContains(FieldContactPhone, v))
}

// ContactPhoneHasPrefix applies the HasPrefix predicate on the "contact_phone" field.
func ContactPhoneHasPrefix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasPrefix(FieldContactPhone, v))
}

// ContactPhoneHasSuffix applies the HasSuffix predicate on the "contact_phone" field.
func ContactPhoneHasSuffix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasSuffix(FieldContactPhone, v))
}

// ContactPhoneEqualFold applies the EqualFold predicate on the "contact_phone" field.
func ContactPhoneEqualFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEqualFold(FieldContactPhone, v))
}

// ContactPhoneContainsFold applies the ContainsFold predicate on the "contact_phone" field.
func ContactPhoneContainsFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContainsFold(FieldContactPhone, v))
}

// StatusEQ applies the EQ predicate on the "status" field.
func StatusEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldStatus, v))
}

// StatusNEQ applies the NEQ predicate on the "status" field.
func StatusNEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldStatus, v))
}

// StatusIn applies the In predicate on the "status" field.
func StatusIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldStatus, vs...))
}

// StatusNotIn applies the NotIn predicate on the "status" field.
func StatusNotIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldStatus, vs...))
}

// StatusGT applies the GT predicate on the "status" field.
func StatusGT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldStatus, v))
}

// StatusGTE applies the GTE predicate on the "status" field.
func StatusGTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldStatus, v))
}

// StatusLT applies the LT predicate on the "status" field.
func StatusLT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldStatus, v))
}

// StatusLTE applies the LTE predicate on the "status" field.
func StatusLTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldStatus, v))
}

// StatusContains applies the Contains predicate on the "status" field.
func StatusContains(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContains(FieldStatus, v))
}

// StatusHasPrefix applies the HasPrefix predicate on the "status" field.
func StatusHasPrefix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasPrefix(FieldStatus, v))
}

// StatusHasSuffix applies the HasSuffix predicate on the "status" field.
func StatusHasSuffix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasSuffix(FieldStatus, v))
}

// StatusEqualFold applies the EqualFold predicate on the "status" field.
func StatusEqualFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEqualFold(FieldStatus, v))
}

// StatusContainsFold applies the ContainsFold predicate on the "status" field.
func StatusContainsFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContainsFold(FieldStatus, v))
}

// AccountSubmissionEnabledEQ applies the EQ predicate on the "account_submission_enabled" field.
func AccountSubmissionEnabledEQ(v bool) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldAccountSubmissionEnabled, v))
}

// AccountSubmissionEnabledNEQ applies the NEQ predicate on the "account_submission_enabled" field.
func AccountSubmissionEnabledNEQ(v bool) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldAccountSubmissionEnabled, v))
}

// NotesEQ applies the EQ predicate on the "notes" field.
func NotesEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldNotes, v))
}

// NotesNEQ applies the NEQ predicate on the "notes" field.
func NotesNEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldNotes, v))
}

// NotesIn applies the In predicate on the "notes" field.
func NotesIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldNotes, vs...))
}

// NotesNotIn applies the NotIn predicate on the "notes" field.
func NotesNotIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldNotes, vs...))
}

// NotesGT applies the GT predicate on the "notes" field.
func NotesGT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldNotes, v))
}

// NotesGTE applies the GTE predicate on the "notes" field.
func NotesGTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldNotes, v))
}

// NotesLT applies the LT predicate on the "notes" field.
func NotesLT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldNotes, v))
}

// NotesLTE applies the LTE predicate on the "notes" field.
func NotesLTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldNotes, v))
}

// NotesContains applies the Contains predicate on the "notes" field.
func NotesContains(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContains(FieldNotes, v))
}

// NotesHasPrefix applies the HasPrefix predicate on the "notes" field.
func NotesHasPrefix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasPrefix(FieldNotes, v))
}

// NotesHasSuffix applies the HasSuffix predicate on the "notes" field.
func NotesHasSuffix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasSuffix(FieldNotes, v))
}

// NotesEqualFold applies the EqualFold predicate on the "notes" field.
func NotesEqualFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEqualFold(FieldNotes, v))
}

// NotesContainsFold applies the ContainsFold predicate on the "notes" field.
func NotesContainsFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContainsFold(FieldNotes, v))
}

// ReviewNoteEQ applies the EQ predicate on the "review_note" field.
func ReviewNoteEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldReviewNote, v))
}

// ReviewNoteNEQ applies the NEQ predicate on the "review_note" field.
func ReviewNoteNEQ(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldReviewNote, v))
}

// ReviewNoteIn applies the In predicate on the "review_note" field.
func ReviewNoteIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldReviewNote, vs...))
}

// ReviewNoteNotIn applies the NotIn predicate on the "review_note" field.
func ReviewNoteNotIn(vs ...string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldReviewNote, vs...))
}

// ReviewNoteGT applies the GT predicate on the "review_note" field.
func ReviewNoteGT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldReviewNote, v))
}

// ReviewNoteGTE applies the GTE predicate on the "review_note" field.
func ReviewNoteGTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldReviewNote, v))
}

// ReviewNoteLT applies the LT predicate on the "review_note" field.
func ReviewNoteLT(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldReviewNote, v))
}

// ReviewNoteLTE applies the LTE predicate on the "review_note" field.
func ReviewNoteLTE(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldReviewNote, v))
}

// ReviewNoteContains applies the Contains predicate on the "review_note" field.
func ReviewNoteContains(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContains(FieldReviewNote, v))
}

// ReviewNoteHasPrefix applies the HasPrefix predicate on the "review_note" field.
func ReviewNoteHasPrefix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasPrefix(FieldReviewNote, v))
}

// ReviewNoteHasSuffix applies the HasSuffix predicate on the "review_note" field.
func ReviewNoteHasSuffix(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldHasSuffix(FieldReviewNote, v))
}

// ReviewNoteEqualFold applies the EqualFold predicate on the "review_note" field.
func ReviewNoteEqualFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEqualFold(FieldReviewNote, v))
}

// ReviewNoteContainsFold applies the ContainsFold predicate on the "review_note" field.
func ReviewNoteContainsFold(v string) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldContainsFold(FieldReviewNote, v))
}

// ReviewedAtEQ applies the EQ predicate on the "reviewed_at" field.
func ReviewedAtEQ(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldReviewedAt, v))
}

// ReviewedAtNEQ applies the NEQ predicate on the "reviewed_at" field.
func ReviewedAtNEQ(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldReviewedAt, v))
}

// ReviewedAtIn applies the In predicate on the "reviewed_at" field.
func ReviewedAtIn(vs ...time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldReviewedAt, vs...))
}

// ReviewedAtNotIn applies the NotIn predicate on the "reviewed_at" field.
func ReviewedAtNotIn(vs ...time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldReviewedAt, vs...))
}

// ReviewedAtGT applies the GT predicate on the "reviewed_at" field.
func ReviewedAtGT(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldReviewedAt, v))
}

// ReviewedAtGTE applies the GTE predicate on the "reviewed_at" field.
func ReviewedAtGTE(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldReviewedAt, v))
}

// ReviewedAtLT applies the LT predicate on the "reviewed_at" field.
func ReviewedAtLT(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldReviewedAt, v))
}

// ReviewedAtLTE applies the LTE predicate on the "reviewed_at" field.
func ReviewedAtLTE(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldReviewedAt, v))
}

// ReviewedAtIsNil applies the IsNil predicate on the "reviewed_at" field.
func ReviewedAtIsNil() predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIsNull(FieldReviewedAt))
}

// ReviewedAtNotNil applies the NotNil predicate on the "reviewed_at" field.
func ReviewedAtNotNil() predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotNull(FieldReviewedAt))
}

// ReviewedByEQ applies the EQ predicate on the "reviewed_by" field.
func ReviewedByEQ(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldReviewedBy, v))
}

// ReviewedByNEQ applies the NEQ predicate on the "reviewed_by" field.
func ReviewedByNEQ(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldReviewedBy, v))
}

// ReviewedByIn applies the In predicate on the "reviewed_by" field.
func ReviewedByIn(vs ...int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldReviewedBy, vs...))
}

// ReviewedByNotIn applies the NotIn predicate on the "reviewed_by" field.
func ReviewedByNotIn(vs ...int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldReviewedBy, vs...))
}

// ReviewedByGT applies the GT predicate on the "reviewed_by" field.
func ReviewedByGT(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldReviewedBy, v))
}

// ReviewedByGTE applies the GTE predicate on the "reviewed_by" field.
func ReviewedByGTE(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldReviewedBy, v))
}

// ReviewedByLT applies the LT predicate on the "reviewed_by" field.
func ReviewedByLT(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldReviewedBy, v))
}

// ReviewedByLTE applies the LTE predicate on the "reviewed_by" field.
func ReviewedByLTE(v int64) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldReviewedBy, v))
}

// ReviewedByIsNil applies the IsNil predicate on the "reviewed_by" field.
func ReviewedByIsNil() predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIsNull(FieldReviewedBy))
}

// ReviewedByNotNil applies the NotNil predicate on the "reviewed_by" field.
func ReviewedByNotNil() predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotNull(FieldReviewedBy))
}

// CreatedAtEQ applies the EQ predicate on the "created_at" field.
func CreatedAtEQ(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldCreatedAt, v))
}

// CreatedAtNEQ applies the NEQ predicate on the "created_at" field.
func CreatedAtNEQ(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldCreatedAt, v))
}

// CreatedAtIn applies the In predicate on the "created_at" field.
func CreatedAtIn(vs ...time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldCreatedAt, vs...))
}

// CreatedAtNotIn applies the NotIn predicate on the "created_at" field.
func CreatedAtNotIn(vs ...time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldCreatedAt, vs...))
}

// CreatedAtGT applies the GT predicate on the "created_at" field.
func CreatedAtGT(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldCreatedAt, v))
}

// CreatedAtGTE applies the GTE predicate on the "created_at" field.
func CreatedAtGTE(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldCreatedAt, v))
}

// CreatedAtLT applies the LT predicate on the "created_at" field.
func CreatedAtLT(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldCreatedAt, v))
}

// CreatedAtLTE applies the LTE predicate on the "created_at" field.
func CreatedAtLTE(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldCreatedAt, v))
}

// UpdatedAtEQ applies the EQ predicate on the "updated_at" field.
func UpdatedAtEQ(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldEQ(FieldUpdatedAt, v))
}

// UpdatedAtNEQ applies the NEQ predicate on the "updated_at" field.
func UpdatedAtNEQ(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNEQ(FieldUpdatedAt, v))
}

// UpdatedAtIn applies the In predicate on the "updated_at" field.
func UpdatedAtIn(vs ...time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldIn(FieldUpdatedAt, vs...))
}

// UpdatedAtNotIn applies the NotIn predicate on the "updated_at" field.
func UpdatedAtNotIn(vs ...time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldNotIn(FieldUpdatedAt, vs...))
}

// UpdatedAtGT applies the GT predicate on the "updated_at" field.
func UpdatedAtGT(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGT(FieldUpdatedAt, v))
}

// UpdatedAtGTE applies the GTE predicate on the "updated_at" field.
func UpdatedAtGTE(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldGTE(FieldUpdatedAt, v))
}

// UpdatedAtLT applies the LT predicate on the "updated_at" field.
func UpdatedAtLT(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLT(FieldUpdatedAt, v))
}

// UpdatedAtLTE applies the LTE predicate on the "updated_at" field.
func UpdatedAtLTE(v time.Time) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.FieldLTE(FieldUpdatedAt, v))
}

// HasUser applies the HasEdge predicate on the "user" edge.
func HasUser() predicate.SupplierProfile {
	return predicate.SupplierProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2O, true, UserTable, UserColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUserWith applies the HasEdge predicate on the "user" edge with a given conditions (other predicates).
func HasUserWith(preds ...predicate.User) predicate.SupplierProfile {
	return predicate.SupplierProfile(func(s *sql.Selector) {
		step := newUserStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasAccounts applies the HasEdge predicate on the "accounts" edge.
func HasAccounts() predicate.SupplierProfile {
	return predicate.SupplierProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, AccountsTable, AccountsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasAccountsWith applies the HasEdge predicate on the "accounts" edge with a given conditions (other predicates).
func HasAccountsWith(preds ...predicate.Account) predicate.SupplierProfile {
	return predicate.SupplierProfile(func(s *sql.Selector) {
		step := newAccountsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// HasUsageLogs applies the HasEdge predicate on the "usage_logs" edge.
func HasUsageLogs() predicate.SupplierProfile {
	return predicate.SupplierProfile(func(s *sql.Selector) {
		step := sqlgraph.NewStep(
			sqlgraph.From(Table, FieldID),
			sqlgraph.Edge(sqlgraph.O2M, false, UsageLogsTable, UsageLogsColumn),
		)
		sqlgraph.HasNeighbors(s, step)
	})
}

// HasUsageLogsWith applies the HasEdge predicate on the "usage_logs" edge with a given conditions (other predicates).
func HasUsageLogsWith(preds ...predicate.UsageLog) predicate.SupplierProfile {
	return predicate.SupplierProfile(func(s *sql.Selector) {
		step := newUsageLogsStep()
		sqlgraph.HasNeighborsWith(s, step, func(s *sql.Selector) {
			for _, p := range preds {
				p(s)
			}
		})
	})
}

// And groups predicates with the AND operator between them.
func And(predicates ...predicate.SupplierProfile) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.AndPredicates(predicates...))
}

// Or groups predicates with the OR operator between them.
func Or(predicates ...predicate.SupplierProfile) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.OrPredicates(predicates...))
}

// Not applies the not operator on the given predicate.
func Not(p predicate.SupplierProfile) predicate.SupplierProfile {
	return predicate.SupplierProfile(sql.NotPredicates(p))
}
