// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/supplierprofile"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupplierProfileCreate is the builder for creating a SupplierProfile entity.
type SupplierProfileCreate struct {
	config
	mutation *SupplierProfileMutation
	hooks    []Hook
	conflict []sql.ConflictOption
}

// SetUserID sets the "user_id" field.
func (_c *SupplierProfileCreate) SetUserID(v int64) *SupplierProfileCreate {
	_c.mutation.SetUserID(v)
	return _c
}

// SetCompanyName sets the "company_name" field.
func (_c *SupplierProfileCreate) SetCompanyName(v string) *SupplierProfileCreate {
	_c.mutation.SetCompanyName(v)
	return _c
}

// SetContactName sets the "contact_name" field.
func (_c *SupplierProfileCreate) SetContactName(v string) *SupplierProfileCreate {
	_c.mutation.SetContactName(v)
	return _c
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableContactName(v *string) *SupplierProfileCreate {
	if v != nil {
		_c.SetContactName(*v)
	}
	return _c
}

// SetContactEmail sets the "contact_email" field.
func (_c *SupplierProfileCreate) SetContactEmail(v string) *SupplierProfileCreate {
	_c.mutation.SetContactEmail(v)
	return _c
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableContactEmail(v *string) *SupplierProfileCreate {
	if v != nil {
		_c.SetContactEmail(*v)
	}
	return _c
}

// SetContactPhone sets the "contact_phone" field.
func (_c *SupplierProfileCreate) SetContactPhone(v string) *SupplierProfileCreate {
	_c.mutation.SetContactPhone(v)
	return _c
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableContactPhone(v *string) *SupplierProfileCreate {
	if v != nil {
		_c.SetContactPhone(*v)
	}
	return _c
}

// SetStatus sets the "status" field.
func (_c *SupplierProfileCreate) SetStatus(v string) *SupplierProfileCreate {
	_c.mutation.SetStatus(v)
	return _c
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableStatus(v *string) *SupplierProfileCreate {
	if v != nil {
		_c.SetStatus(*v)
	}
	return _c
}

// SetSettlementConfig sets the "settlement_config" field.
func (_c *SupplierProfileCreate) SetSettlementConfig(v map[string]interface{}) *SupplierProfileCreate {
	_c.mutation.SetSettlementConfig(v)
	return _c
}

// SetNotes sets the "notes" field.
func (_c *SupplierProfileCreate) SetNotes(v string) *SupplierProfileCreate {
	_c.mutation.SetNotes(v)
	return _c
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableNotes(v *string) *SupplierProfileCreate {
	if v != nil {
		_c.SetNotes(*v)
	}
	return _c
}

// SetReviewNote sets the "review_note" field.
func (_c *SupplierProfileCreate) SetReviewNote(v string) *SupplierProfileCreate {
	_c.mutation.SetReviewNote(v)
	return _c
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableReviewNote(v *string) *SupplierProfileCreate {
	if v != nil {
		_c.SetReviewNote(*v)
	}
	return _c
}

// SetReviewedAt sets the "reviewed_at" field.
func (_c *SupplierProfileCreate) SetReviewedAt(v time.Time) *SupplierProfileCreate {
	_c.mutation.SetReviewedAt(v)
	return _c
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableReviewedAt(v *time.Time) *SupplierProfileCreate {
	if v != nil {
		_c.SetReviewedAt(*v)
	}
	return _c
}

// SetReviewedBy sets the "reviewed_by" field.
func (_c *SupplierProfileCreate) SetReviewedBy(v int64) *SupplierProfileCreate {
	_c.mutation.SetReviewedBy(v)
	return _c
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableReviewedBy(v *int64) *SupplierProfileCreate {
	if v != nil {
		_c.SetReviewedBy(*v)
	}
	return _c
}

// SetCreatedAt sets the "created_at" field.
func (_c *SupplierProfileCreate) SetCreatedAt(v time.Time) *SupplierProfileCreate {
	_c.mutation.SetCreatedAt(v)
	return _c
}

// SetNillableCreatedAt sets the "created_at" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableCreatedAt(v *time.Time) *SupplierProfileCreate {
	if v != nil {
		_c.SetCreatedAt(*v)
	}
	return _c
}

// SetUpdatedAt sets the "updated_at" field.
func (_c *SupplierProfileCreate) SetUpdatedAt(v time.Time) *SupplierProfileCreate {
	_c.mutation.SetUpdatedAt(v)
	return _c
}

// SetNillableUpdatedAt sets the "updated_at" field if the given value is not nil.
func (_c *SupplierProfileCreate) SetNillableUpdatedAt(v *time.Time) *SupplierProfileCreate {
	if v != nil {
		_c.SetUpdatedAt(*v)
	}
	return _c
}

// SetUser sets the "user" edge to the User entity.
func (_c *SupplierProfileCreate) SetUser(v *User) *SupplierProfileCreate {
	return _c.SetUserID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_c *SupplierProfileCreate) AddAccountIDs(ids ...int64) *SupplierProfileCreate {
	_c.mutation.AddAccountIDs(ids...)
	return _c
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_c *SupplierProfileCreate) AddAccounts(v ...*Account) *SupplierProfileCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddAccountIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_c *SupplierProfileCreate) AddUsageLogIDs(ids ...int64) *SupplierProfileCreate {
	_c.mutation.AddUsageLogIDs(ids...)
	return _c
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_c *SupplierProfileCreate) AddUsageLogs(v ...*UsageLog) *SupplierProfileCreate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _c.AddUsageLogIDs(ids...)
}

// Mutation returns the SupplierProfileMutation object of the builder.
func (_c *SupplierProfileCreate) Mutation() *SupplierProfileMutation {
	return _c.mutation
}

// Save creates the SupplierProfile in the database.
func (_c *SupplierProfileCreate) Save(ctx context.Context) (*SupplierProfile, error) {
	_c.defaults()
	return withHooks(ctx, _c.sqlSave, _c.mutation, _c.hooks)
}

// SaveX calls Save and panics if Save returns an error.
func (_c *SupplierProfileCreate) SaveX(ctx context.Context) *SupplierProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierProfileCreate) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierProfileCreate) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_c *SupplierProfileCreate) defaults() {
	if _, ok := _c.mutation.ContactName(); !ok {
		v := supplierprofile.DefaultContactName
		_c.mutation.SetContactName(v)
	}
	if _, ok := _c.mutation.ContactEmail(); !ok {
		v := supplierprofile.DefaultContactEmail
		_c.mutation.SetContactEmail(v)
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		v := supplierprofile.DefaultContactPhone
		_c.mutation.SetContactPhone(v)
	}
	if _, ok := _c.mutation.Status(); !ok {
		v := supplierprofile.DefaultStatus
		_c.mutation.SetStatus(v)
	}
	if _, ok := _c.mutation.SettlementConfig(); !ok {
		v := supplierprofile.DefaultSettlementConfig()
		_c.mutation.SetSettlementConfig(v)
	}
	if _, ok := _c.mutation.Notes(); !ok {
		v := supplierprofile.DefaultNotes
		_c.mutation.SetNotes(v)
	}
	if _, ok := _c.mutation.ReviewNote(); !ok {
		v := supplierprofile.DefaultReviewNote
		_c.mutation.SetReviewNote(v)
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		v := supplierprofile.DefaultCreatedAt()
		_c.mutation.SetCreatedAt(v)
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		v := supplierprofile.DefaultUpdatedAt()
		_c.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_c *SupplierProfileCreate) check() error {
	if _, ok := _c.mutation.UserID(); !ok {
		return &ValidationError{Name: "user_id", err: errors.New(`ent: missing required field "SupplierProfile.user_id"`)}
	}
	if _, ok := _c.mutation.CompanyName(); !ok {
		return &ValidationError{Name: "company_name", err: errors.New(`ent: missing required field "SupplierProfile.company_name"`)}
	}
	if v, ok := _c.mutation.CompanyName(); ok {
		if err := supplierprofile.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.company_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactName(); !ok {
		return &ValidationError{Name: "contact_name", err: errors.New(`ent: missing required field "SupplierProfile.contact_name"`)}
	}
	if v, ok := _c.mutation.ContactName(); ok {
		if err := supplierprofile.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_name": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactEmail(); !ok {
		return &ValidationError{Name: "contact_email", err: errors.New(`ent: missing required field "SupplierProfile.contact_email"`)}
	}
	if v, ok := _c.mutation.ContactEmail(); ok {
		if err := supplierprofile.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_email": %w`, err)}
		}
	}
	if _, ok := _c.mutation.ContactPhone(); !ok {
		return &ValidationError{Name: "contact_phone", err: errors.New(`ent: missing required field "SupplierProfile.contact_phone"`)}
	}
	if v, ok := _c.mutation.ContactPhone(); ok {
		if err := supplierprofile.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_phone": %w`, err)}
		}
	}
	if _, ok := _c.mutation.Status(); !ok {
		return &ValidationError{Name: "status", err: errors.New(`ent: missing required field "SupplierProfile.status"`)}
	}
	if v, ok := _c.mutation.Status(); ok {
		if err := supplierprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.status": %w`, err)}
		}
	}
	if _, ok := _c.mutation.SettlementConfig(); !ok {
		return &ValidationError{Name: "settlement_config", err: errors.New(`ent: missing required field "SupplierProfile.settlement_config"`)}
	}
	if _, ok := _c.mutation.Notes(); !ok {
		return &ValidationError{Name: "notes", err: errors.New(`ent: missing required field "SupplierProfile.notes"`)}
	}
	if _, ok := _c.mutation.ReviewNote(); !ok {
		return &ValidationError{Name: "review_note", err: errors.New(`ent: missing required field "SupplierProfile.review_note"`)}
	}
	if _, ok := _c.mutation.CreatedAt(); !ok {
		return &ValidationError{Name: "created_at", err: errors.New(`ent: missing required field "SupplierProfile.created_at"`)}
	}
	if _, ok := _c.mutation.UpdatedAt(); !ok {
		return &ValidationError{Name: "updated_at", err: errors.New(`ent: missing required field "SupplierProfile.updated_at"`)}
	}
	if len(_c.mutation.UserIDs()) == 0 {
		return &ValidationError{Name: "user", err: errors.New(`ent: missing required edge "SupplierProfile.user"`)}
	}
	return nil
}

func (_c *SupplierProfileCreate) sqlSave(ctx context.Context) (*SupplierProfile, error) {
	if err := _c.check(); err != nil {
		return nil, err
	}
	_node, _spec := _c.createSpec()
	if err := sqlgraph.CreateNode(ctx, _c.driver, _spec); err != nil {
		if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	id := _spec.ID.Value.(int64)
	_node.ID = int64(id)
	_c.mutation.id = &_node.ID
	_c.mutation.done = true
	return _node, nil
}

func (_c *SupplierProfileCreate) createSpec() (*SupplierProfile, *sqlgraph.CreateSpec) {
	var (
		_node = &SupplierProfile{config: _c.config}
		_spec = sqlgraph.NewCreateSpec(supplierprofile.Table, sqlgraph.NewFieldSpec(supplierprofile.FieldID, field.TypeInt64))
	)
	_spec.OnConflict = _c.conflict
	if value, ok := _c.mutation.CompanyName(); ok {
		_spec.SetField(supplierprofile.FieldCompanyName, field.TypeString, value)
		_node.CompanyName = value
	}
	if value, ok := _c.mutation.ContactName(); ok {
		_spec.SetField(supplierprofile.FieldContactName, field.TypeString, value)
		_node.ContactName = value
	}
	if value, ok := _c.mutation.ContactEmail(); ok {
		_spec.SetField(supplierprofile.FieldContactEmail, field.TypeString, value)
		_node.ContactEmail = value
	}
	if value, ok := _c.mutation.ContactPhone(); ok {
		_spec.SetField(supplierprofile.FieldContactPhone, field.TypeString, value)
		_node.ContactPhone = value
	}
	if value, ok := _c.mutation.Status(); ok {
		_spec.SetField(supplierprofile.FieldStatus, field.TypeString, value)
		_node.Status = value
	}
	if value, ok := _c.mutation.SettlementConfig(); ok {
		_spec.SetField(supplierprofile.FieldSettlementConfig, field.TypeJSON, value)
		_node.SettlementConfig = value
	}
	if value, ok := _c.mutation.Notes(); ok {
		_spec.SetField(supplierprofile.FieldNotes, field.TypeString, value)
		_node.Notes = value
	}
	if value, ok := _c.mutation.ReviewNote(); ok {
		_spec.SetField(supplierprofile.FieldReviewNote, field.TypeString, value)
		_node.ReviewNote = value
	}
	if value, ok := _c.mutation.ReviewedAt(); ok {
		_spec.SetField(supplierprofile.FieldReviewedAt, field.TypeTime, value)
		_node.ReviewedAt = &value
	}
	if value, ok := _c.mutation.ReviewedBy(); ok {
		_spec.SetField(supplierprofile.FieldReviewedBy, field.TypeInt64, value)
		_node.ReviewedBy = &value
	}
	if value, ok := _c.mutation.CreatedAt(); ok {
		_spec.SetField(supplierprofile.FieldCreatedAt, field.TypeTime, value)
		_node.CreatedAt = value
	}
	if value, ok := _c.mutation.UpdatedAt(); ok {
		_spec.SetField(supplierprofile.FieldUpdatedAt, field.TypeTime, value)
		_node.UpdatedAt = value
	}
	if nodes := _c.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplierprofile.UserTable,
			Columns: []string{supplierprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_node.UserID = nodes[0]
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.AccountsTable,
			Columns: []string{supplierprofile.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	if nodes := _c.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.UsageLogsTable,
			Columns: []string{supplierprofile.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges = append(_spec.Edges, edge)
	}
	return _node, _spec
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierProfile.Create().
//		SetUserID(v).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierProfileUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierProfileCreate) OnConflict(opts ...sql.ConflictOption) *SupplierProfileUpsertOne {
	_c.conflict = opts
	return &SupplierProfileUpsertOne{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierProfileCreate) OnConflictColumns(columns ...string) *SupplierProfileUpsertOne {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierProfileUpsertOne{
		create: _c,
	}
}

type (
	// SupplierProfileUpsertOne is the builder for "upsert"-ing
	//  one SupplierProfile node.
	SupplierProfileUpsertOne struct {
		create *SupplierProfileCreate
	}

	// SupplierProfileUpsert is the "OnConflict" setter.
	SupplierProfileUpsert struct {
		*sql.UpdateSet
	}
)

// SetUserID sets the "user_id" field.
func (u *SupplierProfileUpsert) SetUserID(v int64) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldUserID, v)
	return u
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateUserID() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldUserID)
	return u
}

// SetCompanyName sets the "company_name" field.
func (u *SupplierProfileUpsert) SetCompanyName(v string) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldCompanyName, v)
	return u
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateCompanyName() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldCompanyName)
	return u
}

// SetContactName sets the "contact_name" field.
func (u *SupplierProfileUpsert) SetContactName(v string) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldContactName, v)
	return u
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateContactName() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldContactName)
	return u
}

// SetContactEmail sets the "contact_email" field.
func (u *SupplierProfileUpsert) SetContactEmail(v string) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldContactEmail, v)
	return u
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateContactEmail() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldContactEmail)
	return u
}

// SetContactPhone sets the "contact_phone" field.
func (u *SupplierProfileUpsert) SetContactPhone(v string) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldContactPhone, v)
	return u
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateContactPhone() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldContactPhone)
	return u
}

// SetStatus sets the "status" field.
func (u *SupplierProfileUpsert) SetStatus(v string) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldStatus, v)
	return u
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateStatus() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldStatus)
	return u
}

// SetSettlementConfig sets the "settlement_config" field.
func (u *SupplierProfileUpsert) SetSettlementConfig(v map[string]interface{}) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldSettlementConfig, v)
	return u
}

// UpdateSettlementConfig sets the "settlement_config" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateSettlementConfig() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldSettlementConfig)
	return u
}

// SetNotes sets the "notes" field.
func (u *SupplierProfileUpsert) SetNotes(v string) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldNotes, v)
	return u
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateNotes() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldNotes)
	return u
}

// SetReviewNote sets the "review_note" field.
func (u *SupplierProfileUpsert) SetReviewNote(v string) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldReviewNote, v)
	return u
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateReviewNote() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldReviewNote)
	return u
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *SupplierProfileUpsert) SetReviewedAt(v time.Time) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldReviewedAt, v)
	return u
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateReviewedAt() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldReviewedAt)
	return u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *SupplierProfileUpsert) ClearReviewedAt() *SupplierProfileUpsert {
	u.SetNull(supplierprofile.FieldReviewedAt)
	return u
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *SupplierProfileUpsert) SetReviewedBy(v int64) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldReviewedBy, v)
	return u
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateReviewedBy() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldReviewedBy)
	return u
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *SupplierProfileUpsert) AddReviewedBy(v int64) *SupplierProfileUpsert {
	u.Add(supplierprofile.FieldReviewedBy, v)
	return u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *SupplierProfileUpsert) ClearReviewedBy() *SupplierProfileUpsert {
	u.SetNull(supplierprofile.FieldReviewedBy)
	return u
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupplierProfileUpsert) SetUpdatedAt(v time.Time) *SupplierProfileUpsert {
	u.Set(supplierprofile.FieldUpdatedAt, v)
	return u
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupplierProfileUpsert) UpdateUpdatedAt() *SupplierProfileUpsert {
	u.SetExcluded(supplierprofile.FieldUpdatedAt)
	return u
}

// UpdateNewValues updates the mutable fields using the new values that were set on create.
// Using this option is equivalent to using:
//
//	client.SupplierProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierProfileUpsertOne) UpdateNewValues() *SupplierProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		if _, exists := u.create.mutation.CreatedAt(); exists {
			s.SetIgnore(supplierprofile.FieldCreatedAt)
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierProfile.Create().
//	    OnConflict(sql.ResolveWithIgnore()).
//	    Exec(ctx)
func (u *SupplierProfileUpsertOne) Ignore() *SupplierProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierProfileUpsertOne) DoNothing() *SupplierProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierProfileCreate.OnConflict
// documentation for more info.
func (u *SupplierProfileUpsertOne) Update(set func(*SupplierProfileUpsert)) *SupplierProfileUpsertOne {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SupplierProfileUpsertOne) SetUserID(v int64) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateUserID() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *SupplierProfileUpsertOne) SetCompanyName(v string) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateCompanyName() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateCompanyName()
	})
}

// SetContactName sets the "contact_name" field.
func (u *SupplierProfileUpsertOne) SetContactName(v string) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateContactName() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateContactName()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *SupplierProfileUpsertOne) SetContactEmail(v string) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateContactEmail() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateContactEmail()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *SupplierProfileUpsertOne) SetContactPhone(v string) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateContactPhone() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateContactPhone()
	})
}

// SetStatus sets the "status" field.
func (u *SupplierProfileUpsertOne) SetStatus(v string) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateStatus() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateStatus()
	})
}

// SetSettlementConfig sets the "settlement_config" field.
func (u *SupplierProfileUpsertOne) SetSettlementConfig(v map[string]interface{}) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetSettlementConfig(v)
	})
}

// UpdateSettlementConfig sets the "settlement_config" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateSettlementConfig() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateSettlementConfig()
	})
}

// SetNotes sets the "notes" field.
func (u *SupplierProfileUpsertOne) SetNotes(v string) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateNotes() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateNotes()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *SupplierProfileUpsertOne) SetReviewNote(v string) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateReviewNote() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateReviewNote()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *SupplierProfileUpsertOne) SetReviewedAt(v time.Time) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateReviewedAt() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *SupplierProfileUpsertOne) ClearReviewedAt() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.ClearReviewedAt()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *SupplierProfileUpsertOne) SetReviewedBy(v int64) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *SupplierProfileUpsertOne) AddReviewedBy(v int64) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateReviewedBy() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *SupplierProfileUpsertOne) ClearReviewedBy() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.ClearReviewedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupplierProfileUpsertOne) SetUpdatedAt(v time.Time) *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupplierProfileUpsertOne) UpdateUpdatedAt() *SupplierProfileUpsertOne {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupplierProfileUpsertOne) Exec(ctx context.Context) error {
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierProfileCreate.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierProfileUpsertOne) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}

// Exec executes the UPSERT query and returns the inserted/updated ID.
func (u *SupplierProfileUpsertOne) ID(ctx context.Context) (id int64, err error) {
	node, err := u.create.Save(ctx)
	if err != nil {
		return id, err
	}
	return node.ID, nil
}

// IDX is like ID, but panics if an error occurs.
func (u *SupplierProfileUpsertOne) IDX(ctx context.Context) int64 {
	id, err := u.ID(ctx)
	if err != nil {
		panic(err)
	}
	return id
}

// SupplierProfileCreateBulk is the builder for creating many SupplierProfile entities in bulk.
type SupplierProfileCreateBulk struct {
	config
	err      error
	builders []*SupplierProfileCreate
	conflict []sql.ConflictOption
}

// Save creates the SupplierProfile entities in the database.
func (_c *SupplierProfileCreateBulk) Save(ctx context.Context) ([]*SupplierProfile, error) {
	if _c.err != nil {
		return nil, _c.err
	}
	specs := make([]*sqlgraph.CreateSpec, len(_c.builders))
	nodes := make([]*SupplierProfile, len(_c.builders))
	mutators := make([]Mutator, len(_c.builders))
	for i := range _c.builders {
		func(i int, root context.Context) {
			builder := _c.builders[i]
			builder.defaults()
			var mut Mutator = MutateFunc(func(ctx context.Context, m Mutation) (Value, error) {
				mutation, ok := m.(*SupplierProfileMutation)
				if !ok {
					return nil, fmt.Errorf("unexpected mutation type %T", m)
				}
				if err := builder.check(); err != nil {
					return nil, err
				}
				builder.mutation = mutation
				var err error
				nodes[i], specs[i] = builder.createSpec()
				if i < len(mutators)-1 {
					_, err = mutators[i+1].Mutate(root, _c.builders[i+1].mutation)
				} else {
					spec := &sqlgraph.BatchCreateSpec{Nodes: specs}
					spec.OnConflict = _c.conflict
					// Invoke the actual operation on the latest mutation in the chain.
					if err = sqlgraph.BatchCreate(ctx, _c.driver, spec); err != nil {
						if sqlgraph.IsConstraintError(err) {
							err = &ConstraintError{msg: err.Error(), wrap: err}
						}
					}
				}
				if err != nil {
					return nil, err
				}
				mutation.id = &nodes[i].ID
				if specs[i].ID.Value != nil {
					id := specs[i].ID.Value.(int64)
					nodes[i].ID = int64(id)
				}
				mutation.done = true
				return nodes[i], nil
			})
			for i := len(builder.hooks) - 1; i >= 0; i-- {
				mut = builder.hooks[i](mut)
			}
			mutators[i] = mut
		}(i, ctx)
	}
	if len(mutators) > 0 {
		if _, err := mutators[0].Mutate(ctx, _c.builders[0].mutation); err != nil {
			return nil, err
		}
	}
	return nodes, nil
}

// SaveX is like Save, but panics if an error occurs.
func (_c *SupplierProfileCreateBulk) SaveX(ctx context.Context) []*SupplierProfile {
	v, err := _c.Save(ctx)
	if err != nil {
		panic(err)
	}
	return v
}

// Exec executes the query.
func (_c *SupplierProfileCreateBulk) Exec(ctx context.Context) error {
	_, err := _c.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_c *SupplierProfileCreateBulk) ExecX(ctx context.Context) {
	if err := _c.Exec(ctx); err != nil {
		panic(err)
	}
}

// OnConflict allows configuring the `ON CONFLICT` / `ON DUPLICATE KEY` clause
// of the `INSERT` statement. For example:
//
//	client.SupplierProfile.CreateBulk(builders...).
//		OnConflict(
//			// Update the row with the new values
//			// the was proposed for insertion.
//			sql.ResolveWithNewValues(),
//		).
//		// Override some of the fields with custom
//		// update values.
//		Update(func(u *ent.SupplierProfileUpsert) {
//			SetUserID(v+v).
//		}).
//		Exec(ctx)
func (_c *SupplierProfileCreateBulk) OnConflict(opts ...sql.ConflictOption) *SupplierProfileUpsertBulk {
	_c.conflict = opts
	return &SupplierProfileUpsertBulk{
		create: _c,
	}
}

// OnConflictColumns calls `OnConflict` and configures the columns
// as conflict target. Using this option is equivalent to using:
//
//	client.SupplierProfile.Create().
//		OnConflict(sql.ConflictColumns(columns...)).
//		Exec(ctx)
func (_c *SupplierProfileCreateBulk) OnConflictColumns(columns ...string) *SupplierProfileUpsertBulk {
	_c.conflict = append(_c.conflict, sql.ConflictColumns(columns...))
	return &SupplierProfileUpsertBulk{
		create: _c,
	}
}

// SupplierProfileUpsertBulk is the builder for "upsert"-ing
// a bulk of SupplierProfile nodes.
type SupplierProfileUpsertBulk struct {
	create *SupplierProfileCreateBulk
}

// UpdateNewValues updates the mutable fields using the new values that
// were set on create. Using this option is equivalent to using:
//
//	client.SupplierProfile.Create().
//		OnConflict(
//			sql.ResolveWithNewValues(),
//		).
//		Exec(ctx)
func (u *SupplierProfileUpsertBulk) UpdateNewValues() *SupplierProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithNewValues())
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(s *sql.UpdateSet) {
		for _, b := range u.create.builders {
			if _, exists := b.mutation.CreatedAt(); exists {
				s.SetIgnore(supplierprofile.FieldCreatedAt)
			}
		}
	}))
	return u
}

// Ignore sets each column to itself in case of conflict.
// Using this option is equivalent to using:
//
//	client.SupplierProfile.Create().
//		OnConflict(sql.ResolveWithIgnore()).
//		Exec(ctx)
func (u *SupplierProfileUpsertBulk) Ignore() *SupplierProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWithIgnore())
	return u
}

// DoNothing configures the conflict_action to `DO NOTHING`.
// Supported only by SQLite and PostgreSQL.
func (u *SupplierProfileUpsertBulk) DoNothing() *SupplierProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.DoNothing())
	return u
}

// Update allows overriding fields `UPDATE` values. See the SupplierProfileCreateBulk.OnConflict
// documentation for more info.
func (u *SupplierProfileUpsertBulk) Update(set func(*SupplierProfileUpsert)) *SupplierProfileUpsertBulk {
	u.create.conflict = append(u.create.conflict, sql.ResolveWith(func(update *sql.UpdateSet) {
		set(&SupplierProfileUpsert{UpdateSet: update})
	}))
	return u
}

// SetUserID sets the "user_id" field.
func (u *SupplierProfileUpsertBulk) SetUserID(v int64) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetUserID(v)
	})
}

// UpdateUserID sets the "user_id" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateUserID() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateUserID()
	})
}

// SetCompanyName sets the "company_name" field.
func (u *SupplierProfileUpsertBulk) SetCompanyName(v string) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetCompanyName(v)
	})
}

// UpdateCompanyName sets the "company_name" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateCompanyName() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateCompanyName()
	})
}

// SetContactName sets the "contact_name" field.
func (u *SupplierProfileUpsertBulk) SetContactName(v string) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetContactName(v)
	})
}

// UpdateContactName sets the "contact_name" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateContactName() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateContactName()
	})
}

// SetContactEmail sets the "contact_email" field.
func (u *SupplierProfileUpsertBulk) SetContactEmail(v string) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetContactEmail(v)
	})
}

// UpdateContactEmail sets the "contact_email" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateContactEmail() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateContactEmail()
	})
}

// SetContactPhone sets the "contact_phone" field.
func (u *SupplierProfileUpsertBulk) SetContactPhone(v string) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetContactPhone(v)
	})
}

// UpdateContactPhone sets the "contact_phone" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateContactPhone() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateContactPhone()
	})
}

// SetStatus sets the "status" field.
func (u *SupplierProfileUpsertBulk) SetStatus(v string) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetStatus(v)
	})
}

// UpdateStatus sets the "status" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateStatus() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateStatus()
	})
}

// SetSettlementConfig sets the "settlement_config" field.
func (u *SupplierProfileUpsertBulk) SetSettlementConfig(v map[string]interface{}) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetSettlementConfig(v)
	})
}

// UpdateSettlementConfig sets the "settlement_config" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateSettlementConfig() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateSettlementConfig()
	})
}

// SetNotes sets the "notes" field.
func (u *SupplierProfileUpsertBulk) SetNotes(v string) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetNotes(v)
	})
}

// UpdateNotes sets the "notes" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateNotes() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateNotes()
	})
}

// SetReviewNote sets the "review_note" field.
func (u *SupplierProfileUpsertBulk) SetReviewNote(v string) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetReviewNote(v)
	})
}

// UpdateReviewNote sets the "review_note" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateReviewNote() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateReviewNote()
	})
}

// SetReviewedAt sets the "reviewed_at" field.
func (u *SupplierProfileUpsertBulk) SetReviewedAt(v time.Time) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetReviewedAt(v)
	})
}

// UpdateReviewedAt sets the "reviewed_at" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateReviewedAt() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateReviewedAt()
	})
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (u *SupplierProfileUpsertBulk) ClearReviewedAt() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.ClearReviewedAt()
	})
}

// SetReviewedBy sets the "reviewed_by" field.
func (u *SupplierProfileUpsertBulk) SetReviewedBy(v int64) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetReviewedBy(v)
	})
}

// AddReviewedBy adds v to the "reviewed_by" field.
func (u *SupplierProfileUpsertBulk) AddReviewedBy(v int64) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.AddReviewedBy(v)
	})
}

// UpdateReviewedBy sets the "reviewed_by" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateReviewedBy() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateReviewedBy()
	})
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (u *SupplierProfileUpsertBulk) ClearReviewedBy() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.ClearReviewedBy()
	})
}

// SetUpdatedAt sets the "updated_at" field.
func (u *SupplierProfileUpsertBulk) SetUpdatedAt(v time.Time) *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.SetUpdatedAt(v)
	})
}

// UpdateUpdatedAt sets the "updated_at" field to the value that was provided on create.
func (u *SupplierProfileUpsertBulk) UpdateUpdatedAt() *SupplierProfileUpsertBulk {
	return u.Update(func(s *SupplierProfileUpsert) {
		s.UpdateUpdatedAt()
	})
}

// Exec executes the query.
func (u *SupplierProfileUpsertBulk) Exec(ctx context.Context) error {
	if u.create.err != nil {
		return u.create.err
	}
	for i, b := range u.create.builders {
		if len(b.conflict) != 0 {
			return fmt.Errorf("ent: OnConflict was set for builder %d. Set it on the SupplierProfileCreateBulk instead", i)
		}
	}
	if len(u.create.conflict) == 0 {
		return errors.New("ent: missing options for SupplierProfileCreateBulk.OnConflict")
	}
	return u.create.Exec(ctx)
}

// ExecX is like Exec, but panics if an error occurs.
func (u *SupplierProfileUpsertBulk) ExecX(ctx context.Context) {
	if err := u.create.Exec(ctx); err != nil {
		panic(err)
	}
}
