// Code generated by ent, DO NOT EDIT.

package ent

import (
	"context"
	"errors"
	"fmt"
	"time"

	"entgo.io/ent/dialect/sql"
	"entgo.io/ent/dialect/sql/sqlgraph"
	"entgo.io/ent/schema/field"
	"github.com/Wei-Shaw/sub2api/ent/account"
	"github.com/Wei-Shaw/sub2api/ent/predicate"
	"github.com/Wei-Shaw/sub2api/ent/supplierprofile"
	"github.com/Wei-Shaw/sub2api/ent/usagelog"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupplierProfileUpdate is the builder for updating SupplierProfile entities.
type SupplierProfileUpdate struct {
	config
	hooks    []Hook
	mutation *SupplierProfileMutation
}

// Where appends a list predicates to the SupplierProfileUpdate builder.
func (_u *SupplierProfileUpdate) Where(ps ...predicate.SupplierProfile) *SupplierProfileUpdate {
	_u.mutation.Where(ps...)
	return _u
}

// SetUserID sets the "user_id" field.
func (_u *SupplierProfileUpdate) SetUserID(v int64) *SupplierProfileUpdate {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableUserID(v *int64) *SupplierProfileUpdate {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *SupplierProfileUpdate) SetCompanyName(v string) *SupplierProfileUpdate {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableCompanyName(v *string) *SupplierProfileUpdate {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *SupplierProfileUpdate) SetContactName(v string) *SupplierProfileUpdate {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableContactName(v *string) *SupplierProfileUpdate {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *SupplierProfileUpdate) SetContactEmail(v string) *SupplierProfileUpdate {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableContactEmail(v *string) *SupplierProfileUpdate {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *SupplierProfileUpdate) SetContactPhone(v string) *SupplierProfileUpdate {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableContactPhone(v *string) *SupplierProfileUpdate {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierProfileUpdate) SetStatus(v string) *SupplierProfileUpdate {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableStatus(v *string) *SupplierProfileUpdate {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAccountSubmissionEnabled sets the "account_submission_enabled" field.
func (_u *SupplierProfileUpdate) SetAccountSubmissionEnabled(v bool) *SupplierProfileUpdate {
	_u.mutation.SetAccountSubmissionEnabled(v)
	return _u
}

// SetNillableAccountSubmissionEnabled sets the "account_submission_enabled" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableAccountSubmissionEnabled(v *bool) *SupplierProfileUpdate {
	if v != nil {
		_u.SetAccountSubmissionEnabled(*v)
	}
	return _u
}

// SetSettlementConfig sets the "settlement_config" field.
func (_u *SupplierProfileUpdate) SetSettlementConfig(v map[string]interface{}) *SupplierProfileUpdate {
	_u.mutation.SetSettlementConfig(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SupplierProfileUpdate) SetNotes(v string) *SupplierProfileUpdate {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableNotes(v *string) *SupplierProfileUpdate {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *SupplierProfileUpdate) SetReviewNote(v string) *SupplierProfileUpdate {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableReviewNote(v *string) *SupplierProfileUpdate {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupplierProfileUpdate) SetReviewedAt(v time.Time) *SupplierProfileUpdate {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableReviewedAt(v *time.Time) *SupplierProfileUpdate {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupplierProfileUpdate) ClearReviewedAt() *SupplierProfileUpdate {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SupplierProfileUpdate) SetReviewedBy(v int64) *SupplierProfileUpdate {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SupplierProfileUpdate) SetNillableReviewedBy(v *int64) *SupplierProfileUpdate {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *SupplierProfileUpdate) AddReviewedBy(v int64) *SupplierProfileUpdate {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SupplierProfileUpdate) ClearReviewedBy() *SupplierProfileUpdate {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierProfileUpdate) SetUpdatedAt(v time.Time) *SupplierProfileUpdate {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupplierProfileUpdate) SetUser(v *User) *SupplierProfileUpdate {
	return _u.SetUserID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SupplierProfileUpdate) AddAccountIDs(ids ...int64) *SupplierProfileUpdate {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SupplierProfileUpdate) AddAccounts(v ...*Account) *SupplierProfileUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *SupplierProfileUpdate) AddUsageLogIDs(ids ...int64) *SupplierProfileUpdate {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *SupplierProfileUpdate) AddUsageLogs(v ...*UsageLog) *SupplierProfileUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the SupplierProfileMutation object of the builder.
func (_u *SupplierProfileUpdate) Mutation() *SupplierProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupplierProfileUpdate) ClearUser() *SupplierProfileUpdate {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SupplierProfileUpdate) ClearAccounts() *SupplierProfileUpdate {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SupplierProfileUpdate) RemoveAccountIDs(ids ...int64) *SupplierProfileUpdate {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SupplierProfileUpdate) RemoveAccounts(v ...*Account) *SupplierProfileUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *SupplierProfileUpdate) ClearUsageLogs() *SupplierProfileUpdate {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *SupplierProfileUpdate) RemoveUsageLogIDs(ids ...int64) *SupplierProfileUpdate {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *SupplierProfileUpdate) RemoveUsageLogs(v ...*UsageLog) *SupplierProfileUpdate {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Save executes the query and returns the number of nodes affected by the update operation.
func (_u *SupplierProfileUpdate) Save(ctx context.Context) (int, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierProfileUpdate) SaveX(ctx context.Context) int {
	affected, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return affected
}

// Exec executes the query.
func (_u *SupplierProfileUpdate) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierProfileUpdate) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierProfileUpdate) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplierprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierProfileUpdate) check() error {
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := supplierprofile.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.company_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactName(); ok {
		if err := supplierprofile.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := supplierprofile.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactPhone(); ok {
		if err := supplierprofile.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplierprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupplierProfile.user"`)
	}
	return nil
}

func (_u *SupplierProfileUpdate) sqlSave(ctx context.Context) (_node int, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplierprofile.Table, supplierprofile.Columns, sqlgraph.NewFieldSpec(supplierprofile.FieldID, field.TypeInt64))
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(supplierprofile.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(supplierprofile.FieldContactName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(supplierprofile.FieldContactEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(supplierprofile.FieldContactPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplierprofile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountSubmissionEnabled(); ok {
		_spec.SetField(supplierprofile.FieldAccountSubmissionEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SettlementConfig(); ok {
		_spec.SetField(supplierprofile.FieldSettlementConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(supplierprofile.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(supplierprofile.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supplierprofile.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supplierprofile.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(supplierprofile.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(supplierprofile.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(supplierprofile.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplierprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplierprofile.UserTable,
			Columns: []string{supplierprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplierprofile.UserTable,
			Columns: []string{supplierprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.AccountsTable,
			Columns: []string{supplierprofile.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.AccountsTable,
			Columns: []string{supplierprofile.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.AccountsTable,
			Columns: []string{supplierprofile.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.UsageLogsTable,
			Columns: []string{supplierprofile.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.UsageLogsTable,
			Columns: []string{supplierprofile.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.UsageLogsTable,
			Columns: []string{supplierprofile.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _node, err = sqlgraph.UpdateNodes(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return 0, err
	}
	_u.mutation.done = true
	return _node, nil
}

// SupplierProfileUpdateOne is the builder for updating a single SupplierProfile entity.
type SupplierProfileUpdateOne struct {
	config
	fields   []string
	hooks    []Hook
	mutation *SupplierProfileMutation
}

// SetUserID sets the "user_id" field.
func (_u *SupplierProfileUpdateOne) SetUserID(v int64) *SupplierProfileUpdateOne {
	_u.mutation.SetUserID(v)
	return _u
}

// SetNillableUserID sets the "user_id" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableUserID(v *int64) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetUserID(*v)
	}
	return _u
}

// SetCompanyName sets the "company_name" field.
func (_u *SupplierProfileUpdateOne) SetCompanyName(v string) *SupplierProfileUpdateOne {
	_u.mutation.SetCompanyName(v)
	return _u
}

// SetNillableCompanyName sets the "company_name" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableCompanyName(v *string) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetCompanyName(*v)
	}
	return _u
}

// SetContactName sets the "contact_name" field.
func (_u *SupplierProfileUpdateOne) SetContactName(v string) *SupplierProfileUpdateOne {
	_u.mutation.SetContactName(v)
	return _u
}

// SetNillableContactName sets the "contact_name" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableContactName(v *string) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetContactName(*v)
	}
	return _u
}

// SetContactEmail sets the "contact_email" field.
func (_u *SupplierProfileUpdateOne) SetContactEmail(v string) *SupplierProfileUpdateOne {
	_u.mutation.SetContactEmail(v)
	return _u
}

// SetNillableContactEmail sets the "contact_email" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableContactEmail(v *string) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetContactEmail(*v)
	}
	return _u
}

// SetContactPhone sets the "contact_phone" field.
func (_u *SupplierProfileUpdateOne) SetContactPhone(v string) *SupplierProfileUpdateOne {
	_u.mutation.SetContactPhone(v)
	return _u
}

// SetNillableContactPhone sets the "contact_phone" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableContactPhone(v *string) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetContactPhone(*v)
	}
	return _u
}

// SetStatus sets the "status" field.
func (_u *SupplierProfileUpdateOne) SetStatus(v string) *SupplierProfileUpdateOne {
	_u.mutation.SetStatus(v)
	return _u
}

// SetNillableStatus sets the "status" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableStatus(v *string) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetStatus(*v)
	}
	return _u
}

// SetAccountSubmissionEnabled sets the "account_submission_enabled" field.
func (_u *SupplierProfileUpdateOne) SetAccountSubmissionEnabled(v bool) *SupplierProfileUpdateOne {
	_u.mutation.SetAccountSubmissionEnabled(v)
	return _u
}

// SetNillableAccountSubmissionEnabled sets the "account_submission_enabled" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableAccountSubmissionEnabled(v *bool) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetAccountSubmissionEnabled(*v)
	}
	return _u
}

// SetSettlementConfig sets the "settlement_config" field.
func (_u *SupplierProfileUpdateOne) SetSettlementConfig(v map[string]interface{}) *SupplierProfileUpdateOne {
	_u.mutation.SetSettlementConfig(v)
	return _u
}

// SetNotes sets the "notes" field.
func (_u *SupplierProfileUpdateOne) SetNotes(v string) *SupplierProfileUpdateOne {
	_u.mutation.SetNotes(v)
	return _u
}

// SetNillableNotes sets the "notes" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableNotes(v *string) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetNotes(*v)
	}
	return _u
}

// SetReviewNote sets the "review_note" field.
func (_u *SupplierProfileUpdateOne) SetReviewNote(v string) *SupplierProfileUpdateOne {
	_u.mutation.SetReviewNote(v)
	return _u
}

// SetNillableReviewNote sets the "review_note" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableReviewNote(v *string) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetReviewNote(*v)
	}
	return _u
}

// SetReviewedAt sets the "reviewed_at" field.
func (_u *SupplierProfileUpdateOne) SetReviewedAt(v time.Time) *SupplierProfileUpdateOne {
	_u.mutation.SetReviewedAt(v)
	return _u
}

// SetNillableReviewedAt sets the "reviewed_at" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableReviewedAt(v *time.Time) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetReviewedAt(*v)
	}
	return _u
}

// ClearReviewedAt clears the value of the "reviewed_at" field.
func (_u *SupplierProfileUpdateOne) ClearReviewedAt() *SupplierProfileUpdateOne {
	_u.mutation.ClearReviewedAt()
	return _u
}

// SetReviewedBy sets the "reviewed_by" field.
func (_u *SupplierProfileUpdateOne) SetReviewedBy(v int64) *SupplierProfileUpdateOne {
	_u.mutation.ResetReviewedBy()
	_u.mutation.SetReviewedBy(v)
	return _u
}

// SetNillableReviewedBy sets the "reviewed_by" field if the given value is not nil.
func (_u *SupplierProfileUpdateOne) SetNillableReviewedBy(v *int64) *SupplierProfileUpdateOne {
	if v != nil {
		_u.SetReviewedBy(*v)
	}
	return _u
}

// AddReviewedBy adds value to the "reviewed_by" field.
func (_u *SupplierProfileUpdateOne) AddReviewedBy(v int64) *SupplierProfileUpdateOne {
	_u.mutation.AddReviewedBy(v)
	return _u
}

// ClearReviewedBy clears the value of the "reviewed_by" field.
func (_u *SupplierProfileUpdateOne) ClearReviewedBy() *SupplierProfileUpdateOne {
	_u.mutation.ClearReviewedBy()
	return _u
}

// SetUpdatedAt sets the "updated_at" field.
func (_u *SupplierProfileUpdateOne) SetUpdatedAt(v time.Time) *SupplierProfileUpdateOne {
	_u.mutation.SetUpdatedAt(v)
	return _u
}

// SetUser sets the "user" edge to the User entity.
func (_u *SupplierProfileUpdateOne) SetUser(v *User) *SupplierProfileUpdateOne {
	return _u.SetUserID(v.ID)
}

// AddAccountIDs adds the "accounts" edge to the Account entity by IDs.
func (_u *SupplierProfileUpdateOne) AddAccountIDs(ids ...int64) *SupplierProfileUpdateOne {
	_u.mutation.AddAccountIDs(ids...)
	return _u
}

// AddAccounts adds the "accounts" edges to the Account entity.
func (_u *SupplierProfileUpdateOne) AddAccounts(v ...*Account) *SupplierProfileUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddAccountIDs(ids...)
}

// AddUsageLogIDs adds the "usage_logs" edge to the UsageLog entity by IDs.
func (_u *SupplierProfileUpdateOne) AddUsageLogIDs(ids ...int64) *SupplierProfileUpdateOne {
	_u.mutation.AddUsageLogIDs(ids...)
	return _u
}

// AddUsageLogs adds the "usage_logs" edges to the UsageLog entity.
func (_u *SupplierProfileUpdateOne) AddUsageLogs(v ...*UsageLog) *SupplierProfileUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.AddUsageLogIDs(ids...)
}

// Mutation returns the SupplierProfileMutation object of the builder.
func (_u *SupplierProfileUpdateOne) Mutation() *SupplierProfileMutation {
	return _u.mutation
}

// ClearUser clears the "user" edge to the User entity.
func (_u *SupplierProfileUpdateOne) ClearUser() *SupplierProfileUpdateOne {
	_u.mutation.ClearUser()
	return _u
}

// ClearAccounts clears all "accounts" edges to the Account entity.
func (_u *SupplierProfileUpdateOne) ClearAccounts() *SupplierProfileUpdateOne {
	_u.mutation.ClearAccounts()
	return _u
}

// RemoveAccountIDs removes the "accounts" edge to Account entities by IDs.
func (_u *SupplierProfileUpdateOne) RemoveAccountIDs(ids ...int64) *SupplierProfileUpdateOne {
	_u.mutation.RemoveAccountIDs(ids...)
	return _u
}

// RemoveAccounts removes "accounts" edges to Account entities.
func (_u *SupplierProfileUpdateOne) RemoveAccounts(v ...*Account) *SupplierProfileUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveAccountIDs(ids...)
}

// ClearUsageLogs clears all "usage_logs" edges to the UsageLog entity.
func (_u *SupplierProfileUpdateOne) ClearUsageLogs() *SupplierProfileUpdateOne {
	_u.mutation.ClearUsageLogs()
	return _u
}

// RemoveUsageLogIDs removes the "usage_logs" edge to UsageLog entities by IDs.
func (_u *SupplierProfileUpdateOne) RemoveUsageLogIDs(ids ...int64) *SupplierProfileUpdateOne {
	_u.mutation.RemoveUsageLogIDs(ids...)
	return _u
}

// RemoveUsageLogs removes "usage_logs" edges to UsageLog entities.
func (_u *SupplierProfileUpdateOne) RemoveUsageLogs(v ...*UsageLog) *SupplierProfileUpdateOne {
	ids := make([]int64, len(v))
	for i := range v {
		ids[i] = v[i].ID
	}
	return _u.RemoveUsageLogIDs(ids...)
}

// Where appends a list predicates to the SupplierProfileUpdate builder.
func (_u *SupplierProfileUpdateOne) Where(ps ...predicate.SupplierProfile) *SupplierProfileUpdateOne {
	_u.mutation.Where(ps...)
	return _u
}

// Select allows selecting one or more fields (columns) of the returned entity.
// The default is selecting all fields defined in the entity schema.
func (_u *SupplierProfileUpdateOne) Select(field string, fields ...string) *SupplierProfileUpdateOne {
	_u.fields = append([]string{field}, fields...)
	return _u
}

// Save executes the query and returns the updated SupplierProfile entity.
func (_u *SupplierProfileUpdateOne) Save(ctx context.Context) (*SupplierProfile, error) {
	_u.defaults()
	return withHooks(ctx, _u.sqlSave, _u.mutation, _u.hooks)
}

// SaveX is like Save, but panics if an error occurs.
func (_u *SupplierProfileUpdateOne) SaveX(ctx context.Context) *SupplierProfile {
	node, err := _u.Save(ctx)
	if err != nil {
		panic(err)
	}
	return node
}

// Exec executes the query on the entity.
func (_u *SupplierProfileUpdateOne) Exec(ctx context.Context) error {
	_, err := _u.Save(ctx)
	return err
}

// ExecX is like Exec, but panics if an error occurs.
func (_u *SupplierProfileUpdateOne) ExecX(ctx context.Context) {
	if err := _u.Exec(ctx); err != nil {
		panic(err)
	}
}

// defaults sets the default values of the builder before save.
func (_u *SupplierProfileUpdateOne) defaults() {
	if _, ok := _u.mutation.UpdatedAt(); !ok {
		v := supplierprofile.UpdateDefaultUpdatedAt()
		_u.mutation.SetUpdatedAt(v)
	}
}

// check runs all checks and user-defined validators on the builder.
func (_u *SupplierProfileUpdateOne) check() error {
	if v, ok := _u.mutation.CompanyName(); ok {
		if err := supplierprofile.CompanyNameValidator(v); err != nil {
			return &ValidationError{Name: "company_name", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.company_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactName(); ok {
		if err := supplierprofile.ContactNameValidator(v); err != nil {
			return &ValidationError{Name: "contact_name", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_name": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactEmail(); ok {
		if err := supplierprofile.ContactEmailValidator(v); err != nil {
			return &ValidationError{Name: "contact_email", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_email": %w`, err)}
		}
	}
	if v, ok := _u.mutation.ContactPhone(); ok {
		if err := supplierprofile.ContactPhoneValidator(v); err != nil {
			return &ValidationError{Name: "contact_phone", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.contact_phone": %w`, err)}
		}
	}
	if v, ok := _u.mutation.Status(); ok {
		if err := supplierprofile.StatusValidator(v); err != nil {
			return &ValidationError{Name: "status", err: fmt.Errorf(`ent: validator failed for field "SupplierProfile.status": %w`, err)}
		}
	}
	if _u.mutation.UserCleared() && len(_u.mutation.UserIDs()) > 0 {
		return errors.New(`ent: clearing a required unique edge "SupplierProfile.user"`)
	}
	return nil
}

func (_u *SupplierProfileUpdateOne) sqlSave(ctx context.Context) (_node *SupplierProfile, err error) {
	if err := _u.check(); err != nil {
		return _node, err
	}
	_spec := sqlgraph.NewUpdateSpec(supplierprofile.Table, supplierprofile.Columns, sqlgraph.NewFieldSpec(supplierprofile.FieldID, field.TypeInt64))
	id, ok := _u.mutation.ID()
	if !ok {
		return nil, &ValidationError{Name: "id", err: errors.New(`ent: missing "SupplierProfile.id" for update`)}
	}
	_spec.Node.ID.Value = id
	if fields := _u.fields; len(fields) > 0 {
		_spec.Node.Columns = make([]string, 0, len(fields))
		_spec.Node.Columns = append(_spec.Node.Columns, supplierprofile.FieldID)
		for _, f := range fields {
			if !supplierprofile.ValidColumn(f) {
				return nil, &ValidationError{Name: f, err: fmt.Errorf("ent: invalid field %q for query", f)}
			}
			if f != supplierprofile.FieldID {
				_spec.Node.Columns = append(_spec.Node.Columns, f)
			}
		}
	}
	if ps := _u.mutation.predicates; len(ps) > 0 {
		_spec.Predicate = func(selector *sql.Selector) {
			for i := range ps {
				ps[i](selector)
			}
		}
	}
	if value, ok := _u.mutation.CompanyName(); ok {
		_spec.SetField(supplierprofile.FieldCompanyName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactName(); ok {
		_spec.SetField(supplierprofile.FieldContactName, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactEmail(); ok {
		_spec.SetField(supplierprofile.FieldContactEmail, field.TypeString, value)
	}
	if value, ok := _u.mutation.ContactPhone(); ok {
		_spec.SetField(supplierprofile.FieldContactPhone, field.TypeString, value)
	}
	if value, ok := _u.mutation.Status(); ok {
		_spec.SetField(supplierprofile.FieldStatus, field.TypeString, value)
	}
	if value, ok := _u.mutation.AccountSubmissionEnabled(); ok {
		_spec.SetField(supplierprofile.FieldAccountSubmissionEnabled, field.TypeBool, value)
	}
	if value, ok := _u.mutation.SettlementConfig(); ok {
		_spec.SetField(supplierprofile.FieldSettlementConfig, field.TypeJSON, value)
	}
	if value, ok := _u.mutation.Notes(); ok {
		_spec.SetField(supplierprofile.FieldNotes, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewNote(); ok {
		_spec.SetField(supplierprofile.FieldReviewNote, field.TypeString, value)
	}
	if value, ok := _u.mutation.ReviewedAt(); ok {
		_spec.SetField(supplierprofile.FieldReviewedAt, field.TypeTime, value)
	}
	if _u.mutation.ReviewedAtCleared() {
		_spec.ClearField(supplierprofile.FieldReviewedAt, field.TypeTime)
	}
	if value, ok := _u.mutation.ReviewedBy(); ok {
		_spec.SetField(supplierprofile.FieldReviewedBy, field.TypeInt64, value)
	}
	if value, ok := _u.mutation.AddedReviewedBy(); ok {
		_spec.AddField(supplierprofile.FieldReviewedBy, field.TypeInt64, value)
	}
	if _u.mutation.ReviewedByCleared() {
		_spec.ClearField(supplierprofile.FieldReviewedBy, field.TypeInt64)
	}
	if value, ok := _u.mutation.UpdatedAt(); ok {
		_spec.SetField(supplierprofile.FieldUpdatedAt, field.TypeTime, value)
	}
	if _u.mutation.UserCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplierprofile.UserTable,
			Columns: []string{supplierprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UserIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2O,
			Inverse: true,
			Table:   supplierprofile.UserTable,
			Columns: []string{supplierprofile.UserColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(user.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.AccountsTable,
			Columns: []string{supplierprofile.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedAccountsIDs(); len(nodes) > 0 && !_u.mutation.AccountsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.AccountsTable,
			Columns: []string{supplierprofile.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.AccountsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.AccountsTable,
			Columns: []string{supplierprofile.AccountsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(account.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	if _u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.UsageLogsTable,
			Columns: []string{supplierprofile.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.RemovedUsageLogsIDs(); len(nodes) > 0 && !_u.mutation.UsageLogsCleared() {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.UsageLogsTable,
			Columns: []string{supplierprofile.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Clear = append(_spec.Edges.Clear, edge)
	}
	if nodes := _u.mutation.UsageLogsIDs(); len(nodes) > 0 {
		edge := &sqlgraph.EdgeSpec{
			Rel:     sqlgraph.O2M,
			Inverse: false,
			Table:   supplierprofile.UsageLogsTable,
			Columns: []string{supplierprofile.UsageLogsColumn},
			Bidi:    false,
			Target: &sqlgraph.EdgeTarget{
				IDSpec: sqlgraph.NewFieldSpec(usagelog.FieldID, field.TypeInt64),
			},
		}
		for _, k := range nodes {
			edge.Target.Nodes = append(edge.Target.Nodes, k)
		}
		_spec.Edges.Add = append(_spec.Edges.Add, edge)
	}
	_node = &SupplierProfile{config: _u.config}
	_spec.Assign = _node.assignValues
	_spec.ScanValues = _node.scanValues
	if err = sqlgraph.UpdateNode(ctx, _u.driver, _spec); err != nil {
		if _, ok := err.(*sqlgraph.NotFoundError); ok {
			err = &NotFoundError{supplierprofile.Label}
		} else if sqlgraph.IsConstraintError(err) {
			err = &ConstraintError{msg: err.Error(), wrap: err}
		}
		return nil, err
	}
	_u.mutation.done = true
	return _node, nil
}
