// Code generated by ent, DO NOT EDIT.

package ent

import (
	"encoding/json"
	"fmt"
	"strings"
	"time"

	"entgo.io/ent"
	"entgo.io/ent/dialect/sql"
	"github.com/Wei-Shaw/sub2api/ent/supplierprofile"
	"github.com/Wei-Shaw/sub2api/ent/user"
)

// SupplierProfile is the model entity for the SupplierProfile schema.
type SupplierProfile struct {
	config `json:"-"`
	// ID of the ent.
	ID int64 `json:"id,omitempty"`
	// UserID holds the value of the "user_id" field.
	UserID int64 `json:"user_id,omitempty"`
	// CompanyName holds the value of the "company_name" field.
	CompanyName string `json:"company_name,omitempty"`
	// ContactName holds the value of the "contact_name" field.
	ContactName string `json:"contact_name,omitempty"`
	// ContactEmail holds the value of the "contact_email" field.
	ContactEmail string `json:"contact_email,omitempty"`
	// ContactPhone holds the value of the "contact_phone" field.
	ContactPhone string `json:"contact_phone,omitempty"`
	// Status holds the value of the "status" field.
	Status string `json:"status,omitempty"`
	// SettlementConfig holds the value of the "settlement_config" field.
	SettlementConfig map[string]interface{} `json:"settlement_config,omitempty"`
	// Notes holds the value of the "notes" field.
	Notes string `json:"notes,omitempty"`
	// ReviewNote holds the value of the "review_note" field.
	ReviewNote string `json:"review_note,omitempty"`
	// ReviewedAt holds the value of the "reviewed_at" field.
	ReviewedAt *time.Time `json:"reviewed_at,omitempty"`
	// ReviewedBy holds the value of the "reviewed_by" field.
	ReviewedBy *int64 `json:"reviewed_by,omitempty"`
	// CreatedAt holds the value of the "created_at" field.
	CreatedAt time.Time `json:"created_at,omitempty"`
	// UpdatedAt holds the value of the "updated_at" field.
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Edges holds the relations/edges for other nodes in the graph.
	// The values are being populated by the SupplierProfileQuery when eager-loading is set.
	Edges        SupplierProfileEdges `json:"edges"`
	selectValues sql.SelectValues
}

// SupplierProfileEdges holds the relations/edges for other nodes in the graph.
type SupplierProfileEdges struct {
	// User holds the value of the user edge.
	User *User `json:"user,omitempty"`
	// Accounts holds the value of the accounts edge.
	Accounts []*Account `json:"accounts,omitempty"`
	// UsageLogs holds the value of the usage_logs edge.
	UsageLogs []*UsageLog `json:"usage_logs,omitempty"`
	// loadedTypes holds the information for reporting if a
	// type was loaded (or requested) in eager-loading or not.
	loadedTypes [3]bool
}

// UserOrErr returns the User value or an error if the edge
// was not loaded in eager-loading, or loaded but was not found.
func (e SupplierProfileEdges) UserOrErr() (*User, error) {
	if e.User != nil {
		return e.User, nil
	} else if e.loadedTypes[0] {
		return nil, &NotFoundError{label: user.Label}
	}
	return nil, &NotLoadedError{edge: "user"}
}

// AccountsOrErr returns the Accounts value or an error if the edge
// was not loaded in eager-loading.
func (e SupplierProfileEdges) AccountsOrErr() ([]*Account, error) {
	if e.loadedTypes[1] {
		return e.Accounts, nil
	}
	return nil, &NotLoadedError{edge: "accounts"}
}

// UsageLogsOrErr returns the UsageLogs value or an error if the edge
// was not loaded in eager-loading.
func (e SupplierProfileEdges) UsageLogsOrErr() ([]*UsageLog, error) {
	if e.loadedTypes[2] {
		return e.UsageLogs, nil
	}
	return nil, &NotLoadedError{edge: "usage_logs"}
}

// scanValues returns the types for scanning values from sql.Rows.
func (*SupplierProfile) scanValues(columns []string) ([]any, error) {
	values := make([]any, len(columns))
	for i := range columns {
		switch columns[i] {
		case supplierprofile.FieldSettlementConfig:
			values[i] = new([]byte)
		case supplierprofile.FieldID, supplierprofile.FieldUserID, supplierprofile.FieldReviewedBy:
			values[i] = new(sql.NullInt64)
		case supplierprofile.FieldCompanyName, supplierprofile.FieldContactName, supplierprofile.FieldContactEmail, supplierprofile.FieldContactPhone, supplierprofile.FieldStatus, supplierprofile.FieldNotes, supplierprofile.FieldReviewNote:
			values[i] = new(sql.NullString)
		case supplierprofile.FieldReviewedAt, supplierprofile.FieldCreatedAt, supplierprofile.FieldUpdatedAt:
			values[i] = new(sql.NullTime)
		default:
			values[i] = new(sql.UnknownType)
		}
	}
	return values, nil
}

// assignValues assigns the values that were returned from sql.Rows (after scanning)
// to the SupplierProfile fields.
func (_m *SupplierProfile) assignValues(columns []string, values []any) error {
	if m, n := len(values), len(columns); m < n {
		return fmt.Errorf("mismatch number of scan values: %d != %d", m, n)
	}
	for i := range columns {
		switch columns[i] {
		case supplierprofile.FieldID:
			value, ok := values[i].(*sql.NullInt64)
			if !ok {
				return fmt.Errorf("unexpected type %T for field id", value)
			}
			_m.ID = int64(value.Int64)
		case supplierprofile.FieldUserID:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field user_id", values[i])
			} else if value.Valid {
				_m.UserID = value.Int64
			}
		case supplierprofile.FieldCompanyName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field company_name", values[i])
			} else if value.Valid {
				_m.CompanyName = value.String
			}
		case supplierprofile.FieldContactName:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_name", values[i])
			} else if value.Valid {
				_m.ContactName = value.String
			}
		case supplierprofile.FieldContactEmail:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_email", values[i])
			} else if value.Valid {
				_m.ContactEmail = value.String
			}
		case supplierprofile.FieldContactPhone:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field contact_phone", values[i])
			} else if value.Valid {
				_m.ContactPhone = value.String
			}
		case supplierprofile.FieldStatus:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field status", values[i])
			} else if value.Valid {
				_m.Status = value.String
			}
		case supplierprofile.FieldSettlementConfig:
			if value, ok := values[i].(*[]byte); !ok {
				return fmt.Errorf("unexpected type %T for field settlement_config", values[i])
			} else if value != nil && len(*value) > 0 {
				if err := json.Unmarshal(*value, &_m.SettlementConfig); err != nil {
					return fmt.Errorf("unmarshal field settlement_config: %w", err)
				}
			}
		case supplierprofile.FieldNotes:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field notes", values[i])
			} else if value.Valid {
				_m.Notes = value.String
			}
		case supplierprofile.FieldReviewNote:
			if value, ok := values[i].(*sql.NullString); !ok {
				return fmt.Errorf("unexpected type %T for field review_note", values[i])
			} else if value.Valid {
				_m.ReviewNote = value.String
			}
		case supplierprofile.FieldReviewedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_at", values[i])
			} else if value.Valid {
				_m.ReviewedAt = new(time.Time)
				*_m.ReviewedAt = value.Time
			}
		case supplierprofile.FieldReviewedBy:
			if value, ok := values[i].(*sql.NullInt64); !ok {
				return fmt.Errorf("unexpected type %T for field reviewed_by", values[i])
			} else if value.Valid {
				_m.ReviewedBy = new(int64)
				*_m.ReviewedBy = value.Int64
			}
		case supplierprofile.FieldCreatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field created_at", values[i])
			} else if value.Valid {
				_m.CreatedAt = value.Time
			}
		case supplierprofile.FieldUpdatedAt:
			if value, ok := values[i].(*sql.NullTime); !ok {
				return fmt.Errorf("unexpected type %T for field updated_at", values[i])
			} else if value.Valid {
				_m.UpdatedAt = value.Time
			}
		default:
			_m.selectValues.Set(columns[i], values[i])
		}
	}
	return nil
}

// Value returns the ent.Value that was dynamically selected and assigned to the SupplierProfile.
// This includes values selected through modifiers, order, etc.
func (_m *SupplierProfile) Value(name string) (ent.Value, error) {
	return _m.selectValues.Get(name)
}

// QueryUser queries the "user" edge of the SupplierProfile entity.
func (_m *SupplierProfile) QueryUser() *UserQuery {
	return NewSupplierProfileClient(_m.config).QueryUser(_m)
}

// QueryAccounts queries the "accounts" edge of the SupplierProfile entity.
func (_m *SupplierProfile) QueryAccounts() *AccountQuery {
	return NewSupplierProfileClient(_m.config).QueryAccounts(_m)
}

// QueryUsageLogs queries the "usage_logs" edge of the SupplierProfile entity.
func (_m *SupplierProfile) QueryUsageLogs() *UsageLogQuery {
	return NewSupplierProfileClient(_m.config).QueryUsageLogs(_m)
}

// Update returns a builder for updating this SupplierProfile.
// Note that you need to call SupplierProfile.Unwrap() before calling this method if this SupplierProfile
// was returned from a transaction, and the transaction was committed or rolled back.
func (_m *SupplierProfile) Update() *SupplierProfileUpdateOne {
	return NewSupplierProfileClient(_m.config).UpdateOne(_m)
}

// Unwrap unwraps the SupplierProfile entity that was returned from a transaction after it was closed,
// so that all future queries will be executed through the driver which created the transaction.
func (_m *SupplierProfile) Unwrap() *SupplierProfile {
	_tx, ok := _m.config.driver.(*txDriver)
	if !ok {
		panic("ent: SupplierProfile is not a transactional entity")
	}
	_m.config.driver = _tx.drv
	return _m
}

// String implements the fmt.Stringer.
func (_m *SupplierProfile) String() string {
	var builder strings.Builder
	builder.WriteString("SupplierProfile(")
	builder.WriteString(fmt.Sprintf("id=%v, ", _m.ID))
	builder.WriteString("user_id=")
	builder.WriteString(fmt.Sprintf("%v", _m.UserID))
	builder.WriteString(", ")
	builder.WriteString("company_name=")
	builder.WriteString(_m.CompanyName)
	builder.WriteString(", ")
	builder.WriteString("contact_name=")
	builder.WriteString(_m.ContactName)
	builder.WriteString(", ")
	builder.WriteString("contact_email=")
	builder.WriteString(_m.ContactEmail)
	builder.WriteString(", ")
	builder.WriteString("contact_phone=")
	builder.WriteString(_m.ContactPhone)
	builder.WriteString(", ")
	builder.WriteString("status=")
	builder.WriteString(_m.Status)
	builder.WriteString(", ")
	builder.WriteString("settlement_config=")
	builder.WriteString(fmt.Sprintf("%v", _m.SettlementConfig))
	builder.WriteString(", ")
	builder.WriteString("notes=")
	builder.WriteString(_m.Notes)
	builder.WriteString(", ")
	builder.WriteString("review_note=")
	builder.WriteString(_m.ReviewNote)
	builder.WriteString(", ")
	if v := _m.ReviewedAt; v != nil {
		builder.WriteString("reviewed_at=")
		builder.WriteString(v.Format(time.ANSIC))
	}
	builder.WriteString(", ")
	if v := _m.ReviewedBy; v != nil {
		builder.WriteString("reviewed_by=")
		builder.WriteString(fmt.Sprintf("%v", *v))
	}
	builder.WriteString(", ")
	builder.WriteString("created_at=")
	builder.WriteString(_m.CreatedAt.Format(time.ANSIC))
	builder.WriteString(", ")
	builder.WriteString("updated_at=")
	builder.WriteString(_m.UpdatedAt.Format(time.ANSIC))
	builder.WriteByte(')')
	return builder.String()
}

// SupplierProfiles is a parsable slice of SupplierProfile.
type SupplierProfiles []*SupplierProfile
